# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_Adc9228_top_0_0/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_0
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_Adc9228_top_0_0/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_1
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/02c8/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/e2dd/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/6180/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/a08d/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/6851/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/82bb/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/ec67/hdl
  } {
      D:/SoftwareInstall/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/SoftwareInstall/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      D:/SoftwareInstall/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_Adc9228_top_0_0/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_0
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_Adc9228_top_0_0/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_1
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/02c8/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/e2dd/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/6180/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/a08d/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/6851/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/82bb/hdl/verilog
    d:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ipshared/ec67/hdl
  } {
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_Adc9228_top_0_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_TriggerCh_3_1_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_processing_system7_0_1_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_TriggerCh_0_2_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_TriggerCh_1_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_TriggerCh_2_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_smartconnect_0_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_smartconnect_0_1_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_smartconnect_1_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_smartconnect_2_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_rst_Adc9228_top_0_100M_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_xlconstant_0_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_xlconcat_0_1_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_ila_0_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_xbar_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_rst_Adc9228_top_0_10M_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_rst_Adc9228_top_0_10M_1_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_rst_Adc9228_top_0_10M_2_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_rst_Adc9228_top_0_10M_3_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_rst_Adc9228_top_0_10M_4_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/realtime/Adc3444_TCP_auto_pc_0_stub.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/synth/Adc3444_TCP.v
      D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/hdl/Adc3444_TCP_wrapper.v
    }
      rt::read_vhdl -lib xpm D:/SoftwareInstall/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Adc3444_TCP_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/HangZhouFile_byx/ZynqProject_v17/Adc9228_TCP_System/.Xil/Vivado-18764-DESKTOP-3EGBBSD/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
