# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/Adc3444_TCP/Adc3444_TCP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP || ORIG_REF_NAME==Adc3444_TCP} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_Adc9228_top_0_0/Adc3444_TCP_Adc9228_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_Adc9228_top_0_0 || ORIG_REF_NAME==Adc3444_TCP_Adc9228_top_0_0} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_3_1/Adc3444_TCP_TriggerCh_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_TriggerCh_3_1 || ORIG_REF_NAME==Adc3444_TCP_TriggerCh_3_1} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_processing_system7_0_1/Adc3444_TCP_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_processing_system7_0_1 || ORIG_REF_NAME==Adc3444_TCP_processing_system7_0_1} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_0_2/Adc3444_TCP_TriggerCh_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_TriggerCh_0_2 || ORIG_REF_NAME==Adc3444_TCP_TriggerCh_0_2} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_1_0/Adc3444_TCP_TriggerCh_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_TriggerCh_1_0 || ORIG_REF_NAME==Adc3444_TCP_TriggerCh_1_0} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_2_0/Adc3444_TCP_TriggerCh_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_TriggerCh_2_0 || ORIG_REF_NAME==Adc3444_TCP_TriggerCh_2_0} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_ps7_0_axi_periph_0/Adc3444_TCP_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_ps7_0_axi_periph_0 || ORIG_REF_NAME==Adc3444_TCP_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_xlconcat_0_1/Adc3444_TCP_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_xlconcat_0_1 || ORIG_REF_NAME==Adc3444_TCP_xlconcat_0_1} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_xbar_0/Adc3444_TCP_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_xbar_0 || ORIG_REF_NAME==Adc3444_TCP_xbar_0} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_rst_Adc9228_top_0_10M_2/Adc3444_TCP_rst_Adc9228_top_0_10M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_rst_Adc9228_top_0_10M_2 || ORIG_REF_NAME==Adc3444_TCP_rst_Adc9228_top_0_10M_2} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_system_ila_0_0/Adc3444_TCP_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_system_ila_0_0 || ORIG_REF_NAME==Adc3444_TCP_system_ila_0_0} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/Adc3444_TCP_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_smartconnect_0_0 || ORIG_REF_NAME==Adc3444_TCP_smartconnect_0_0} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/Adc3444_TCP_smartconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_smartconnect_0_1 || ORIG_REF_NAME==Adc3444_TCP_smartconnect_0_1} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_2/Adc3444_TCP_smartconnect_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_smartconnect_0_2 || ORIG_REF_NAME==Adc3444_TCP_smartconnect_0_2} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_3/Adc3444_TCP_smartconnect_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_smartconnect_0_3 || ORIG_REF_NAME==Adc3444_TCP_smartconnect_0_3} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_system_ila_0_1/Adc3444_TCP_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_system_ila_0_1 || ORIG_REF_NAME==Adc3444_TCP_system_ila_0_1} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_system_Trig_Ch0_0/Adc3444_TCP_system_Trig_Ch0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_system_Trig_Ch0_0 || ORIG_REF_NAME==Adc3444_TCP_system_Trig_Ch0_0} -quiet] -quiet

# IP: bd/Adc3444_TCP/ip/Adc3444_TCP_auto_pc_0/Adc3444_TCP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Adc3444_TCP_auto_pc_0 || ORIG_REF_NAME==Adc3444_TCP_auto_pc_0} -quiet] -quiet

# XDC: bd/Adc3444_TCP/Adc3444_TCP_ooc.xdc
