# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ZynqProject_v17/Adc9228_TCP_System_v3/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_xbar_0/Adc3444_TCP_xbar_0.xci
# IP: The module: 'Adc3444_TCP_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZynqProject_v17/Adc9228_TCP_System_v3/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_xbar_0/Adc3444_TCP_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Adc3444_TCP_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/ZynqProject_v17/Adc9228_TCP_System_v3/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_xbar_0/Adc3444_TCP_xbar_0.xci
# IP: The module: 'Adc3444_TCP_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ZynqProject_v17/Adc9228_TCP_System_v3/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_xbar_0/Adc3444_TCP_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Adc3444_TCP_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
