# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.cache/wt [current_project]
set_property parent.project_path E:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/ZynqProject_v17/Adc9228_top_axi
  e:/TriggerCh
} [current_project]
set_property ip_output_repo e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/hdl/Adc3444_TCP_wrapper.v
add_files E:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/Adc3444_TCP.bd
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_Adc9228_top_0_0/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_Adc9228_top_0_0/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_Adc9228_top_0_0/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_Adc9228_top_0_0/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_3_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_3_1/ip/ila_0/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_3_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_3_1/ip/ila_1/ila_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_processing_system7_0_1/Adc3444_TCP_processing_system7_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_0_2/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_0_2/ip/ila_0/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_0_2/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_0_2/ip/ila_1/ila_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_1_0/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_1_0/ip/ila_0/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_1_0/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_1_0/ip/ila_1/ila_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_2_0/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_2_0/ip/ila_0/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_2_0/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_TriggerCh_2_0/ip/ila_1/ila_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/bd_0/ip/ip_5/bd_ca73_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/bd_0/ip/ip_11/bd_ca73_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/bd_0/ip/ip_6/bd_ca73_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/bd_0/ip/ip_7/bd_ca73_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/bd_0/ip/ip_8/bd_ca73_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/bd_0/ip/ip_9/bd_ca73_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/bd_0/ip/ip_10/bd_ca73_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/bd_0/ip/ip_1/bd_ca73_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/bd_0/ip/ip_1/bd_ca73_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/bd_0/ip/ip_5/bd_0ab2_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/bd_0/ip/ip_11/bd_0ab2_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/bd_0/ip/ip_6/bd_0ab2_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/bd_0/ip/ip_7/bd_0ab2_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/bd_0/ip/ip_8/bd_0ab2_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/bd_0/ip/ip_9/bd_0ab2_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/bd_0/ip/ip_10/bd_0ab2_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/bd_0/ip/ip_1/bd_0ab2_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/bd_0/ip/ip_1/bd_0ab2_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_0_1/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/bd_0/ip/ip_5/bd_0a22_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/bd_0/ip/ip_11/bd_0a22_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/bd_0/ip/ip_6/bd_0a22_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/bd_0/ip/ip_7/bd_0a22_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/bd_0/ip/ip_8/bd_0a22_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/bd_0/ip/ip_9/bd_0a22_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/bd_0/ip/ip_10/bd_0a22_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/bd_0/ip/ip_1/bd_0a22_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/bd_0/ip/ip_1/bd_0a22_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/bd_0/ip/ip_5/bd_0ad2_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/bd_0/ip/ip_11/bd_0ad2_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/bd_0/ip/ip_6/bd_0ad2_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/bd_0/ip/ip_7/bd_0ad2_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/bd_0/ip/ip_8/bd_0ad2_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/bd_0/ip/ip_9/bd_0ad2_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/bd_0/ip/ip_10/bd_0ad2_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/bd_0/ip/ip_1/bd_0ad2_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/bd_0/ip/ip_1/bd_0ad2_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_smartconnect_2_0/ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_ila_0_0/Adc3444_TCP_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_xbar_0/Adc3444_TCP_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_rst_Adc9228_top_0_10M_2/Adc3444_TCP_rst_Adc9228_top_0_10M_2_board.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_rst_Adc9228_top_0_10M_2/Adc3444_TCP_rst_Adc9228_top_0_10M_2.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_rst_Adc9228_top_0_10M_2/Adc3444_TCP_rst_Adc9228_top_0_10M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_util_ds_buf_0_0/Adc3444_TCP_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_util_ds_buf_0_0/Adc3444_TCP_util_ds_buf_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_util_ds_buf_0_0/Adc3444_TCP_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/ip/Adc3444_TCP_auto_pc_0/Adc3444_TCP_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/sources_1/bd/Adc3444_TCP/Adc3444_TCP_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files E:/ZynqProject_v17/Adc9228_TCP_System_v2/Adc3444_TCP_main.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Adc3444_TCP_wrapper -part xc7z020clg400-1 -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Adc3444_TCP_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Adc3444_TCP_wrapper_utilization_synth.rpt -pb Adc3444_TCP_wrapper_utilization_synth.pb"
