# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.cache/wt [current_project]
set_property parent.project_path E:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  e:/ZynqProject_v17/Adc9228_top_axi_v2
  e:/ZynqProject_v17/Adc9228_top_axi_v2/ZynqProject_v17
  e:/ZynqProject_v17/Adc9228_top_axi_v2/hangzhoufile_byx
} [current_project]
set_property ip_output_repo e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/ZynqProject_v17/Adc9228_top_axi_v2/src/AD_control.v
  E:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/new/Delay3Claps.v
  E:/ZynqProject_v17/Adc9228_top_axi_v2/src/adc_1.v
  E:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/new/generate_vaild.v
  E:/ZynqProject_v17/Adc9228_top_axi_v2/src/io.v
  E:/ZynqProject_v17/Adc9228_top_axi_v2/src/pulse_generator.v
  E:/ZynqProject_v17/Adc9228_top_axi_v2/src/sys_ctrl.v
  E:/ZynqProject_v17/Adc9228_top_axi_v2/src/Adc9228_top.v
}
read_ip -quiet E:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.xci
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_board.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_ooc.xdc]

read_ip -quiet E:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc]

read_ip -quiet E:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet E:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet E:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ZynqProject_v17/Adc9228_top_axi_v2/Adc9228_top_axi.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Adc9228_top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Adc9228_top.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file Adc9228_top_utilization_synth.rpt -pb Adc9228_top_utilization_synth.pb"
