# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/clk_wiz_3/clk_wiz_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_3 || ORIG_REF_NAME==clk_wiz_3} -quiet] -quiet
